name: Docker CI/CD

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY_NAME: ic-devops-todo-api
  DOCKERHUB_REPOSITORY_NAME2: ic-devops-todo-worker
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker meta for api
        id: api
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY_NAME }}
          tags: |
            type=sha,prefix=,suffix=
      
      - name: Docker meta for worker
        id: worker
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY_NAME2 }}
          tags: |
            type=sha,prefix=,suffix=

      - name: Build and push api
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.api.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.worker.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Assume AWS IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to EC2
        run: |
          # Create SSH key file
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Get the image tag from the build job
          IMAGE_TAG="${{ github.sha }}"
          INSTANCE_IP="${{ secrets.INSTANCE_IP }}"
          # Test SSH connection first
          ssh -i private_key.pem -o StrictHostKeyChecking=no -o ConnectTimeout=10 ubuntu@$INSTANCE_IP "echo 'SSH connection successful'"

          # SSH into EC2 and deploy
          ssh -i private_key.pem -o StrictHostKeyChecking=no -T ubuntu@$INSTANCE_IP << EOF
          
          
          # Go to app directory (where repo + compose.yml is cloned)
          cd ~/todo-backendICDevOps
          git fetch origin
          git reset --hard origin/master
          
          #Login to Docker Hub
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin
          IMAGE_TAG=${{ github.sha }} docker compose pull 
          IMAGE_TAG=${{ github.sha }} docker compose up -d
          
          # Clean up old images to save space
          docker image prune -f
          EOF

          # Clean up SSH key
          rm private_key.pem
